/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface UserCollection {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  set_number: string;
  user_id: string;
}

export interface UserRating {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  rating: number;
  set_number: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface UserWishlist {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  scale: Generated<number>;
  set_number: string;
  user_id: string;
}

export interface DB {
  user_collection: UserCollection;
  user_rating: UserRating;
  user_wishlist: UserWishlist;
}
